//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Yeah/Input/WeaponControll.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @WeaponControll: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @WeaponControll()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""WeaponControll"",
    ""maps"": [
        {
            ""name"": ""OnWeaponControll"",
            ""id"": ""01ead258-22f0-44a3-8b30-1f31be1a14de"",
            ""actions"": [
                {
                    ""name"": ""SwitchWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""c0b9660c-3a13-4cd5-a0c5-b076ece75fac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bf8bb1ae-f2fe-4563-bd2a-411e447f158c"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnWeaponControll
        m_OnWeaponControll = asset.FindActionMap("OnWeaponControll", throwIfNotFound: true);
        m_OnWeaponControll_SwitchWeapon = m_OnWeaponControll.FindAction("SwitchWeapon", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnWeaponControll
    private readonly InputActionMap m_OnWeaponControll;
    private List<IOnWeaponControllActions> m_OnWeaponControllActionsCallbackInterfaces = new List<IOnWeaponControllActions>();
    private readonly InputAction m_OnWeaponControll_SwitchWeapon;
    public struct OnWeaponControllActions
    {
        private @WeaponControll m_Wrapper;
        public OnWeaponControllActions(@WeaponControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchWeapon => m_Wrapper.m_OnWeaponControll_SwitchWeapon;
        public InputActionMap Get() { return m_Wrapper.m_OnWeaponControll; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnWeaponControllActions set) { return set.Get(); }
        public void AddCallbacks(IOnWeaponControllActions instance)
        {
            if (instance == null || m_Wrapper.m_OnWeaponControllActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnWeaponControllActionsCallbackInterfaces.Add(instance);
            @SwitchWeapon.started += instance.OnSwitchWeapon;
            @SwitchWeapon.performed += instance.OnSwitchWeapon;
            @SwitchWeapon.canceled += instance.OnSwitchWeapon;
        }

        private void UnregisterCallbacks(IOnWeaponControllActions instance)
        {
            @SwitchWeapon.started -= instance.OnSwitchWeapon;
            @SwitchWeapon.performed -= instance.OnSwitchWeapon;
            @SwitchWeapon.canceled -= instance.OnSwitchWeapon;
        }

        public void RemoveCallbacks(IOnWeaponControllActions instance)
        {
            if (m_Wrapper.m_OnWeaponControllActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnWeaponControllActions instance)
        {
            foreach (var item in m_Wrapper.m_OnWeaponControllActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnWeaponControllActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnWeaponControllActions @OnWeaponControll => new OnWeaponControllActions(this);
    public interface IOnWeaponControllActions
    {
        void OnSwitchWeapon(InputAction.CallbackContext context);
    }
}
